// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.AuditLogExports", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateRangeEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateRangeStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExportFormat")
                        .HasColumnType("longtext");

                    b.Property<string>("ExportStatus")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExportedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("audit_log_exports");
                });

            modelBuilder.Entity("backend.Models.AuditLogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("backend.Models.FeeConfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("base_fee")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("effective_from")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("effective_until")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("grace_period_minutes")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("vehicle_type_id")
                        .HasColumnType("int");

                    b.Property<int>("zone_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("created_by");

                    b.HasIndex("vehicle_type_id");

                    b.HasIndex("zone_id");

                    b.ToTable("fee_configs");
                });

            modelBuilder.Entity("backend.Models.FeeTier", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("duration_minutes")
                        .HasColumnType("int");

                    b.Property<int>("fee_amount")
                        .HasColumnType("int");

                    b.Property<int>("fee_config_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_last_tier")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("tier_order")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("fee_config_id");

                    b.ToTable("fee_tiers");
                });

            modelBuilder.Entity("backend.Models.Gate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gate_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("location_desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("zone_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("gates");
                });

            modelBuilder.Entity("backend.Models.GateDevice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("device_type")
                        .HasColumnType("longtext");

                    b.Property<string>("error_message")
                        .HasColumnType("text");

                    b.Property<int>("gate_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("las_ping_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("gate_devices");
                });

            modelBuilder.Entity("backend.Models.HolidayRate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("applies_to_vehicle_type_id")
                        .HasColumnType("int");

                    b.Property<int>("applies_to_zone_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("date_aend")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_start")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("multiplier")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("override_fee")
                        .HasColumnType("int");

                    b.Property<string>("rate_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("applies_to_vehicle_type_id");

                    b.HasIndex("applies_to_zone_id");

                    b.ToTable("holiday_rates");
                });

            modelBuilder.Entity("backend.Models.MidtransCallback", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("error_message")
                        .HasColumnType("text");

                    b.Property<string>("midtrans_order_id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("payment_id")
                        .HasColumnType("int");

                    b.Property<bool>("processed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("processed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("raw_payload")
                        .HasColumnType("json");

                    b.Property<DateTime?>("received_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("signature_valid")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.HasIndex("payment_id");

                    b.ToTable("midtrans_callbacks");
                });

            modelBuilder.Entity("backend.Models.OcrConfigs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AutoAcceptThreshold")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ocr_configs");
                });

            modelBuilder.Entity("backend.Models.OcrResults", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OcrJobId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PlateDetected")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RawOutput")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("VerifiedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("ocr_results");
                });

            modelBuilder.Entity("backend.Models.OcrReviewLogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ManualPlate")
                        .HasColumnType("longtext");

                    b.Property<bool>("Match")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("OcrConfidence")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("OcrPlate")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OcrResultId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("ocr_review_logs");
                });

            modelBuilder.Entity("backend.Models.OverrideConfigs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EscalationNotifyUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxOverridesPerDay")
                        .HasColumnType("int");

                    b.Property<int>("MaxOverridesPerWeek")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("override_configs");
                });

            modelBuilder.Entity("backend.Models.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<int>("cash_change")
                        .HasColumnType("int");

                    b.Property<int>("cash_tendered")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("handled_by_user_id")
                        .HasColumnType("int");

                    b.Property<string>("method")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("midtrans_order_id")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("midtrans_status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("midtrans_transaction_id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("paid_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("qris_expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("qris_url")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("transaction_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("handled_by_user_id");

                    b.HasIndex("transaction_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("backend.Models.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("node")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("node")
                        .IsUnique();

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("backend.Models.Refund", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("approved_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("midtrans_refund_id")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("payment_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("processed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("refund_amount")
                        .HasColumnType("int");

                    b.Property<int>("requested_by")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("transaction_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("approved_by");

                    b.HasIndex("payment_id");

                    b.HasIndex("requested_by");

                    b.HasIndex("transaction_id");

                    b.ToTable("refunds");
                });

            modelBuilder.Entity("backend.Models.RfidCard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("card_uid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("deactivated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("deactivated_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("vehicle_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("rfid_cards");
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("backend.Models.RolePermission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("granted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("granted_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("permission_id")
                        .HasColumnType("int");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("permission_id");

                    b.HasIndex("role_id");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("backend.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("calculated_fee")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("entry_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("entry_gate_id")
                        .HasColumnType("int");

                    b.Property<string>("entry_method")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("entry_photo_url")
                        .HasColumnType("text");

                    b.Property<string>("entry_qr_code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("exit_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("exit_gate_id")
                        .HasColumnType("int");

                    b.Property<string>("exit_method")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("fee_config_id")
                        .HasColumnType("int");

                    b.Property<int>("holiday_rate_id")
                        .HasColumnType("int");

                    b.Property<bool>("receipt_printed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("receipt_printed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("rfid_card_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("transaction_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("vehicle_id")
                        .HasColumnType("int");

                    b.Property<int>("zone_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("entry_gate_id");

                    b.HasIndex("exit_gate_id");

                    b.HasIndex("fee_config_id");

                    b.HasIndex("holiday_rate_id");

                    b.HasIndex("rfid_card_id");

                    b.HasIndex("vehicle_id");

                    b.HasIndex("zone_id");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("backend.Models.UserLoginLogs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("attempt_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("attempted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("failure_reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("success")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("user_agent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("user_login_logs");
                });

            modelBuilder.Entity("backend.Models.UserLoginStats", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("is_locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_attempt_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("last_failed_ip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("last_success_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("locked_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("locked_reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("total_attempts")
                        .HasColumnType("int");

                    b.Property<int>("total_failed_attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("user_login_stats");
                });

            modelBuilder.Entity("backend.Models.UserSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("token_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_agent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("backend.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("backend.Models.Vehicle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("plate_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("vehicle_type_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("vehicle_type_id");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("backend.Models.VehicleTypes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("minimum_fee")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("vehicle_types");
                });

            modelBuilder.Entity("backend.Models.Zone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("additional_fee")
                        .HasColumnType("int");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("zones");
                });

            modelBuilder.Entity("backend.Models.FeeConfig", b =>
                {
                    b.HasOne("backend.Models.Users", "creator")
                        .WithMany()
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.VehicleTypes", "vehicle_type")
                        .WithMany()
                        .HasForeignKey("vehicle_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Zone", "zone")
                        .WithMany()
                        .HasForeignKey("zone_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("creator");

                    b.Navigation("vehicle_type");

                    b.Navigation("zone");
                });

            modelBuilder.Entity("backend.Models.FeeTier", b =>
                {
                    b.HasOne("backend.Models.FeeConfig", "fee_config")
                        .WithMany()
                        .HasForeignKey("fee_config_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fee_config");
                });

            modelBuilder.Entity("backend.Models.HolidayRate", b =>
                {
                    b.HasOne("backend.Models.VehicleTypes", "vehicle_type")
                        .WithMany()
                        .HasForeignKey("applies_to_vehicle_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Zone", "zone")
                        .WithMany()
                        .HasForeignKey("applies_to_zone_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vehicle_type");

                    b.Navigation("zone");
                });

            modelBuilder.Entity("backend.Models.MidtransCallback", b =>
                {
                    b.HasOne("backend.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("payment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("backend.Models.Payment", b =>
                {
                    b.HasOne("backend.Models.Users", "HandledByUser")
                        .WithMany()
                        .HasForeignKey("handled_by_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("transaction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HandledByUser");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("backend.Models.Refund", b =>
                {
                    b.HasOne("backend.Models.Users", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("approved_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("payment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Users", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("requested_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("transaction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Payment");

                    b.Navigation("RequestedByUser");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("backend.Models.RolePermission", b =>
                {
                    b.HasOne("backend.Models.Permission", "Permissions")
                        .WithMany()
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissions");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("backend.Models.Transaction", b =>
                {
                    b.HasOne("backend.Models.Gate", "EntryGate")
                        .WithMany()
                        .HasForeignKey("entry_gate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Gate", "ExitGate")
                        .WithMany()
                        .HasForeignKey("exit_gate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.FeeConfig", "FeeConfig")
                        .WithMany()
                        .HasForeignKey("fee_config_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.HolidayRate", "HolidayRate")
                        .WithMany()
                        .HasForeignKey("holiday_rate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.RfidCard", "RfidCard")
                        .WithMany()
                        .HasForeignKey("rfid_card_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("vehicle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("zone_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntryGate");

                    b.Navigation("ExitGate");

                    b.Navigation("FeeConfig");

                    b.Navigation("HolidayRate");

                    b.Navigation("RfidCard");

                    b.Navigation("Vehicle");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("backend.Models.UserLoginLogs", b =>
                {
                    b.HasOne("backend.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Models.UserLoginStats", b =>
                {
                    b.HasOne("backend.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Models.Users", b =>
                {
                    b.HasOne("backend.Models.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("backend.Models.Vehicle", b =>
                {
                    b.HasOne("backend.Models.VehicleTypes", "VehicleTypes")
                        .WithMany()
                        .HasForeignKey("vehicle_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
