// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.AuditLogExports", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateRangeEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateRangeStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExportFormat")
                        .HasColumnType("longtext");

                    b.Property<string>("ExportStatus")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExportedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("audit_log_exports");
                });

            modelBuilder.Entity("backend.Models.AuditLogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("backend.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 806, DateTimeKind.Unspecified).AddTicks(661), new TimeSpan(0, 0, 0, 0, 0)),
                            name = "Budi Santoso",
                            role_id = 3,
                            updated_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 806, DateTimeKind.Unspecified).AddTicks(1132), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 806, DateTimeKind.Unspecified).AddTicks(2023), new TimeSpan(0, 0, 0, 0, 0)),
                            name = "Siti Nurhaliza",
                            role_id = 3,
                            updated_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 806, DateTimeKind.Unspecified).AddTicks(2024), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 806, DateTimeKind.Unspecified).AddTicks(2059), new TimeSpan(0, 0, 0, 0, 0)),
                            name = "Ahmad Wijaya",
                            role_id = 3,
                            updated_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 806, DateTimeKind.Unspecified).AddTicks(2060), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            id = 4,
                            created_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 806, DateTimeKind.Unspecified).AddTicks(2065), new TimeSpan(0, 0, 0, 0, 0)),
                            name = "Rina Kusuma",
                            role_id = 4,
                            updated_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 806, DateTimeKind.Unspecified).AddTicks(2065), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            id = 5,
                            created_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 806, DateTimeKind.Unspecified).AddTicks(2070), new TimeSpan(0, 0, 0, 0, 0)),
                            name = "Dedi Gunawan",
                            role_id = 3,
                            updated_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 806, DateTimeKind.Unspecified).AddTicks(2071), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("backend.Models.FeeConfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("base_fee")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("effective_from")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("effective_until")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("grace_period_minutes")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("vehicle_type_id")
                        .HasColumnType("int");

                    b.Property<int>("zone_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("created_by");

                    b.HasIndex("vehicle_type_id");

                    b.HasIndex("zone_id");

                    b.ToTable("fee_configs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            base_fee = 10000,
                            created_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            created_by = 1,
                            effective_from = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            grace_period_minutes = 15,
                            is_active = true,
                            updated_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            vehicle_type_id = 2,
                            zone_id = 1
                        },
                        new
                        {
                            id = 2,
                            base_fee = 5000,
                            created_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            created_by = 1,
                            effective_from = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            grace_period_minutes = 10,
                            is_active = true,
                            updated_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            vehicle_type_id = 1,
                            zone_id = 1
                        },
                        new
                        {
                            id = 3,
                            base_fee = 20000,
                            created_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            created_by = 1,
                            effective_from = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            grace_period_minutes = 20,
                            is_active = true,
                            updated_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            vehicle_type_id = 2,
                            zone_id = 5
                        },
                        new
                        {
                            id = 4,
                            base_fee = 25000,
                            created_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            created_by = 2,
                            effective_from = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            grace_period_minutes = 30,
                            is_active = true,
                            updated_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            vehicle_type_id = 3,
                            zone_id = 2
                        },
                        new
                        {
                            id = 5,
                            base_fee = 20000,
                            created_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            created_by = 2,
                            effective_from = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            grace_period_minutes = 15,
                            is_active = true,
                            updated_at = new DateTimeOffset(new DateTime(2026, 4, 25, 1, 41, 29, 804, DateTimeKind.Unspecified).AddTicks(6913), new TimeSpan(0, 0, 0, 0, 0)),
                            vehicle_type_id = 4,
                            zone_id = 3
                        });
                });

            modelBuilder.Entity("backend.Models.FeeTier", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("duration_minutes")
                        .HasColumnType("int");

                    b.Property<int>("fee_amount")
                        .HasColumnType("int");

                    b.Property<int>("fee_config_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_last_tier")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("tier_order")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("fee_config_id");

                    b.ToTable("fee_tiers");

                    b.HasData(
                        new
                        {
                            id = 1,
                            duration_minutes = 60,
                            fee_amount = 10000,
                            fee_config_id = 1,
                            is_last_tier = true,
                            tier_order = 1
                        },
                        new
                        {
                            id = 2,
                            duration_minutes = 60,
                            fee_amount = 5000,
                            fee_config_id = 2,
                            is_last_tier = true,
                            tier_order = 1
                        },
                        new
                        {
                            id = 3,
                            duration_minutes = 60,
                            fee_amount = 20000,
                            fee_config_id = 3,
                            is_last_tier = true,
                            tier_order = 1
                        },
                        new
                        {
                            id = 4,
                            duration_minutes = 60,
                            fee_amount = 25000,
                            fee_config_id = 4,
                            is_last_tier = true,
                            tier_order = 1
                        },
                        new
                        {
                            id = 5,
                            duration_minutes = 60,
                            fee_amount = 20000,
                            fee_config_id = 5,
                            is_last_tier = true,
                            tier_order = 1
                        });
                });

            modelBuilder.Entity("backend.Models.Gate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gate_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("location_desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("zone_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("gates");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 3, 26, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            gate_type = "entrance",
                            is_active = true,
                            location_desc = "Main entrance gate Zona A",
                            name = "Gate A1 - Entrance",
                            updated_at = new DateTime(2026, 3, 26, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            zone_id = 1
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 3, 26, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            gate_type = "exit",
                            is_active = true,
                            location_desc = "Main exit gate Zona A",
                            name = "Gate A2 - Exit",
                            updated_at = new DateTime(2026, 3, 31, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            zone_id = 1
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(2026, 4, 5, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            gate_type = "entrance",
                            is_active = true,
                            location_desc = "Second floor entrance Zona B",
                            name = "Gate B1 - Entrance",
                            updated_at = new DateTime(2026, 4, 5, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            zone_id = 2
                        },
                        new
                        {
                            id = 4,
                            created_at = new DateTime(2026, 4, 10, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            gate_type = "entrance",
                            is_active = true,
                            location_desc = "Third floor entrance Zona C",
                            name = "Gate C1 - Entrance",
                            updated_at = new DateTime(2026, 4, 15, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            zone_id = 3
                        },
                        new
                        {
                            id = 5,
                            created_at = new DateTime(2026, 4, 20, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            gate_type = "entrance",
                            is_active = true,
                            location_desc = "Premium VIP entrance Zona E",
                            name = "Gate E1 - VIP",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            zone_id = 5
                        });
                });

            modelBuilder.Entity("backend.Models.GateDevice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("device_type")
                        .HasColumnType("longtext");

                    b.Property<string>("error_message")
                        .HasColumnType("text");

                    b.Property<int>("gate_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("las_ping_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("uniqUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("gate_devices");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            device_type = "RFID_READER",
                            gate_id = 1,
                            las_ping_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            status = true,
                            uniqUrl = "https://device.parkir.com/gate1",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            device_type = "BARRIER_ARM",
                            gate_id = 2,
                            las_ping_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            status = true,
                            uniqUrl = "https://device.parkir.com/gate2",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            device_type = "RFID_READER",
                            gate_id = 3,
                            las_ping_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            status = true,
                            uniqUrl = "https://device.parkir.com/gate3",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 4,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            device_type = "BARRIER_ARM",
                            error_message = "Connection timeout",
                            gate_id = 4,
                            las_ping_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            status = false,
                            uniqUrl = "https://device.parkir.com/gate4",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 5,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            device_type = "CAMERA",
                            gate_id = 5,
                            las_ping_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            status = true,
                            uniqUrl = "https://device.parkir.com/gate5",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        });
                });

            modelBuilder.Entity("backend.Models.GateDeviceAds", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("gate_device_id")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("gate_device_ads");
                });

            modelBuilder.Entity("backend.Models.HolidayRate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("applies_to_vehicle_type_id")
                        .HasColumnType("int");

                    b.Property<int>("applies_to_zone_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("date_aend")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_start")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("multiplier")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("override_fee")
                        .HasColumnType("int");

                    b.Property<string>("rate_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("applies_to_vehicle_type_id");

                    b.HasIndex("applies_to_zone_id");

                    b.ToTable("holiday_rates");

                    b.HasData(
                        new
                        {
                            id = 1,
                            applies_to_vehicle_type_id = 2,
                            applies_to_zone_id = 1,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            date_aend = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            date_start = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            multiplier = 1.5f,
                            name = "Lebaran 2026",
                            override_fee = 0,
                            rate_type = "multiplier",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 2,
                            applies_to_vehicle_type_id = 1,
                            applies_to_zone_id = 5,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            date_aend = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            date_start = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            multiplier = 1f,
                            name = "Tahun Baru",
                            override_fee = 25000,
                            rate_type = "override",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 3,
                            applies_to_vehicle_type_id = 3,
                            applies_to_zone_id = 2,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            date_aend = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            date_start = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            multiplier = 2f,
                            name = "Hari Raya",
                            override_fee = 0,
                            rate_type = "multiplier",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 4,
                            applies_to_vehicle_type_id = 2,
                            applies_to_zone_id = 5,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            date_aend = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            date_start = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            multiplier = 1f,
                            name = "Malam Tahun Baru",
                            override_fee = 50000,
                            rate_type = "override",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 5,
                            applies_to_vehicle_type_id = 4,
                            applies_to_zone_id = 3,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            date_aend = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            date_start = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            multiplier = 1.3f,
                            name = "Libur Nasional",
                            override_fee = 0,
                            rate_type = "multiplier",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        });
                });

            modelBuilder.Entity("backend.Models.MembershipPackage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("package_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("time_period_month")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("membership_packages");
                });

            modelBuilder.Entity("backend.Models.MidtransCallback", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("error_message")
                        .HasColumnType("text");

                    b.Property<string>("midtrans_order_id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("payment_id")
                        .HasColumnType("int");

                    b.Property<bool>("processed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("processed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("raw_payload")
                        .HasColumnType("json");

                    b.Property<DateTime?>("received_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("signature_valid")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.HasIndex("payment_id");

                    b.ToTable("midtrans_callbacks");
                });

            modelBuilder.Entity("backend.Models.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<int>("cash_change")
                        .HasColumnType("int");

                    b.Property<int>("cash_tendered")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("handled_by_user_id")
                        .HasColumnType("int");

                    b.Property<string>("method")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("midtrans_order_id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("midtrans_status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("midtrans_transaction_id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("paid_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("qris_expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("qris_url")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("transaction_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("handled_by_user_id");

                    b.HasIndex("transaction_id");

                    b.ToTable("payments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            amount = 10000,
                            cash_change = 0,
                            cash_tendered = 10000,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            handled_by_user_id = 1,
                            method = "cash",
                            midtrans_order_id = "MID001",
                            paid_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            status = "paid",
                            transaction_id = 1,
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 2,
                            amount = 5000,
                            cash_change = 0,
                            cash_tendered = 0,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            handled_by_user_id = 2,
                            method = "qris",
                            midtrans_order_id = "MID002",
                            midtrans_status = "pending",
                            qris_expires_at = new DateTime(2026, 4, 25, 8, 46, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            qris_url = "qris_001.png",
                            status = "pending",
                            transaction_id = 2,
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 3,
                            amount = 0,
                            cash_change = 0,
                            cash_tendered = 0,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            handled_by_user_id = 3,
                            method = "card",
                            midtrans_order_id = "MID003",
                            midtrans_status = "pending",
                            status = "unpaid",
                            transaction_id = 3,
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 4,
                            amount = 20000,
                            cash_change = 0,
                            cash_tendered = 20000,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            handled_by_user_id = 4,
                            method = "cash",
                            midtrans_order_id = "MID004",
                            paid_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            status = "paid",
                            transaction_id = 4,
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 5,
                            amount = 25000,
                            cash_change = 0,
                            cash_tendered = 0,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            handled_by_user_id = 5,
                            method = "qris",
                            midtrans_order_id = "MID005",
                            midtrans_status = "settlement",
                            midtrans_transaction_id = "MTX005",
                            paid_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            qris_expires_at = new DateTime(2026, 4, 25, 8, 51, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            qris_url = "qris_005.png",
                            status = "paid",
                            transaction_id = 5,
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        });
                });

            modelBuilder.Entity("backend.Models.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("node")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("node")
                        .IsUnique();

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 798, DateTimeKind.Local).AddTicks(4080),
                            description = "View permissions",
                            node = "permission.view"
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 798, DateTimeKind.Local).AddTicks(4541),
                            description = "Create permissions",
                            node = "permission.create"
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 798, DateTimeKind.Local).AddTicks(4544),
                            description = "Edit permissions",
                            node = "permission.edit"
                        },
                        new
                        {
                            id = 4,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 798, DateTimeKind.Local).AddTicks(4546),
                            description = "Delete permissions",
                            node = "permission.delete"
                        },
                        new
                        {
                            id = 5,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 798, DateTimeKind.Local).AddTicks(4549),
                            description = "Manage zones",
                            node = "zone.manage"
                        });
                });

            modelBuilder.Entity("backend.Models.RfidCard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("card_uid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deactivated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("deactivated_by")
                        .HasColumnType("longtext");

                    b.Property<int?>("employee_id")
                        .HasColumnType("int");

                    b.Property<bool?>("is_guest")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("is_member")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("pic_tenant_id")
                        .HasColumnType("int");

                    b.Property<int?>("vehicle_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("employee_id");

                    b.HasIndex("pic_tenant_id");

                    b.HasIndex("vehicle_id");

                    b.ToTable("rfid_cards");

                    b.HasData(
                        new
                        {
                            id = 1,
                            card_uid = "08D4B2C0",
                            created_at = new DateTime(2026, 3, 26, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            is_guest = false,
                            is_member = true,
                            vehicle_id = 1
                        },
                        new
                        {
                            id = 2,
                            card_uid = "08D4B2C1",
                            created_at = new DateTime(2026, 4, 5, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            is_guest = false,
                            is_member = true,
                            vehicle_id = 2
                        },
                        new
                        {
                            id = 3,
                            card_uid = "08D4B2C2",
                            created_at = new DateTime(2026, 4, 10, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            is_guest = true,
                            is_member = false,
                            vehicle_id = 3
                        },
                        new
                        {
                            id = 4,
                            card_uid = "08D4B2C3",
                            created_at = new DateTime(2026, 4, 15, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            employee_id = 1,
                            is_guest = false,
                            is_member = false
                        },
                        new
                        {
                            id = 5,
                            card_uid = "08D4B2C4",
                            created_at = new DateTime(2026, 4, 20, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            employee_id = 2,
                            is_guest = false,
                            is_member = false
                        });
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            deleted_at = new DateTime(2026, 4, 25, 8, 41, 29, 800, DateTimeKind.Local).AddTicks(1066),
                            description = "Full access to all system features",
                            name = "Super Admin",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            deleted_at = new DateTime(2026, 4, 25, 8, 41, 29, 800, DateTimeKind.Local).AddTicks(3703),
                            description = "Administrative access",
                            name = "Admin",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            deleted_at = new DateTime(2026, 4, 25, 8, 41, 29, 800, DateTimeKind.Local).AddTicks(3712),
                            description = "Gate and parking operator",
                            name = "Operator",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 4,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            deleted_at = new DateTime(2026, 4, 25, 8, 41, 29, 800, DateTimeKind.Local).AddTicks(3716),
                            description = "Zone manager and reporting",
                            name = "Manager",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 5,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            deleted_at = new DateTime(2026, 4, 25, 8, 41, 29, 800, DateTimeKind.Local).AddTicks(3791),
                            description = "View-only access",
                            name = "Viewer",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        });
                });

            modelBuilder.Entity("backend.Models.RolePermission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("granted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("granted_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("permission_id")
                        .HasColumnType("int");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("permission_id");

                    b.HasIndex("role_id");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            id = 1,
                            granted_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            granted_by = "System",
                            permission_id = 1,
                            role_id = 1
                        },
                        new
                        {
                            id = 2,
                            granted_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            granted_by = "System",
                            permission_id = 2,
                            role_id = 1
                        },
                        new
                        {
                            id = 3,
                            granted_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            granted_by = "System",
                            permission_id = 3,
                            role_id = 1
                        },
                        new
                        {
                            id = 4,
                            granted_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            granted_by = "System",
                            permission_id = 4,
                            role_id = 1
                        },
                        new
                        {
                            id = 5,
                            granted_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            granted_by = "System",
                            permission_id = 5,
                            role_id = 1
                        });
                });

            modelBuilder.Entity("backend.Models.TenantMember", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("due_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("membership_id")
                        .HasColumnType("int");

                    b.Property<string>("pic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("start_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status_membership")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tenant_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("total_bill")
                        .HasColumnType("int");

                    b.Property<int>("total_current_payment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("membership_id");

                    b.HasIndex("user_id");

                    b.ToTable("tenant_members");
                });

            modelBuilder.Entity("backend.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("calculated_fee")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("entry_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("entry_gate_id")
                        .HasColumnType("int");

                    b.Property<string>("entry_method")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("entry_photo_url")
                        .HasColumnType("text");

                    b.Property<string>("entry_qr_code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("exit_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("exit_gate_id")
                        .HasColumnType("int");

                    b.Property<string>("exit_method")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int?>("fee_config_id")
                        .HasColumnType("int");

                    b.Property<int?>("holiday_rate_id")
                        .HasColumnType("int");

                    b.Property<int?>("member_vehicle_id")
                        .HasColumnType("int");

                    b.Property<bool?>("receipt_printed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("receipt_printed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("rfid_card_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("total_payment")
                        .HasColumnType("int");

                    b.Property<string>("transaction_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("vehicle_type_id")
                        .HasColumnType("int");

                    b.Property<int?>("zone_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("entry_gate_id");

                    b.HasIndex("exit_gate_id");

                    b.HasIndex("fee_config_id");

                    b.HasIndex("holiday_rate_id");

                    b.HasIndex("member_vehicle_id");

                    b.HasIndex("rfid_card_id");

                    b.HasIndex("vehicle_type_id");

                    b.HasIndex("zone_id");

                    b.ToTable("transactions");

                    b.HasData(
                        new
                        {
                            id = 1,
                            calculated_fee = 10000,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            entry_at = new DateTime(2026, 4, 25, 6, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            entry_gate_id = 1,
                            entry_method = "RFID",
                            entry_photo_url = "photo1.jpg",
                            entry_qr_code = "QR001",
                            exit_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            exit_gate_id = 2,
                            exit_method = "RFID",
                            fee_config_id = 1,
                            receipt_printed = true,
                            receipt_printed_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            status = "completed",
                            transaction_code = "TRX001",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 807, DateTimeKind.Local).AddTicks(3778),
                            vehicle_type_id = 2,
                            zone_id = 1
                        },
                        new
                        {
                            id = 2,
                            calculated_fee = 5000,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            entry_at = new DateTime(2026, 4, 25, 7, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            entry_gate_id = 1,
                            entry_method = "RFID",
                            entry_photo_url = "photo2.jpg",
                            entry_qr_code = "QR002",
                            exit_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            exit_gate_id = 2,
                            exit_method = "MANUAL",
                            fee_config_id = 2,
                            receipt_printed = true,
                            receipt_printed_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            status = "completed",
                            transaction_code = "TRX002",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 808, DateTimeKind.Local).AddTicks(1540),
                            vehicle_type_id = 1,
                            zone_id = 1
                        },
                        new
                        {
                            id = 3,
                            calculated_fee = 0,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            entry_at = new DateTime(2026, 4, 25, 5, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            entry_gate_id = 3,
                            entry_method = "OCR",
                            entry_photo_url = "photo3.jpg",
                            entry_qr_code = "QR003",
                            exit_gate_id = 4,
                            exit_method = "MANUAL",
                            fee_config_id = 4,
                            receipt_printed = false,
                            status = "pending",
                            transaction_code = "TRX003",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 808, DateTimeKind.Local).AddTicks(1554),
                            vehicle_type_id = 3,
                            zone_id = 2
                        },
                        new
                        {
                            id = 4,
                            calculated_fee = 20000,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            entry_at = new DateTime(2026, 4, 25, 4, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            entry_gate_id = 2,
                            entry_method = "RFID",
                            entry_photo_url = "photo4.jpg",
                            entry_qr_code = "QR004",
                            exit_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            exit_gate_id = 5,
                            exit_method = "RFID",
                            fee_config_id = 5,
                            member_vehicle_id = 4,
                            receipt_printed = true,
                            receipt_printed_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            status = "completed",
                            transaction_code = "TRX004",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 808, DateTimeKind.Local).AddTicks(1561),
                            vehicle_type_id = 4,
                            zone_id = 1
                        },
                        new
                        {
                            id = 5,
                            calculated_fee = 25000,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            entry_at = new DateTime(2026, 4, 25, 3, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            entry_gate_id = 4,
                            entry_method = "OCR",
                            entry_photo_url = "photo5.jpg",
                            entry_qr_code = "QR005",
                            exit_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            exit_gate_id = 5,
                            exit_method = "OCR",
                            fee_config_id = 3,
                            member_vehicle_id = 5,
                            receipt_printed = true,
                            receipt_printed_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            status = "completed",
                            transaction_code = "TRX005",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 808, DateTimeKind.Local).AddTicks(1973),
                            vehicle_type_id = 2,
                            zone_id = 5
                        });
                });

            modelBuilder.Entity("backend.Models.UserLoginLogs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("attempt_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("attempted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("failure_reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("success")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("user_agent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("user_login_logs");
                });

            modelBuilder.Entity("backend.Models.UserLoginStats", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("is_locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_attempt_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("last_failed_ip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("last_success_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("locked_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("locked_reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("total_attempts")
                        .HasColumnType("int");

                    b.Property<int>("total_failed_attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("user_login_stats");
                });

            modelBuilder.Entity("backend.Models.UserSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("refresh_token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_agent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("backend.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            deleted_at = new DateTime(2026, 4, 25, 8, 41, 29, 800, DateTimeKind.Local).AddTicks(6512),
                            email = "superadmin@parkir.local",
                            is_active = true,
                            name = "Super Administrator",
                            password_hash = "12345",
                            role_id = 1,
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            deleted_at = new DateTime(2026, 4, 25, 8, 41, 29, 801, DateTimeKind.Local).AddTicks(222),
                            email = "admin@parkir.local",
                            is_active = true,
                            name = "Admin User",
                            password_hash = "12345",
                            role_id = 2,
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            deleted_at = new DateTime(2026, 4, 25, 8, 41, 29, 801, DateTimeKind.Local).AddTicks(231),
                            email = "operator1@parkir.local",
                            is_active = true,
                            name = "Gate Operator 1",
                            password_hash = "12345",
                            role_id = 3,
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 4,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            deleted_at = new DateTime(2026, 4, 25, 8, 41, 29, 801, DateTimeKind.Local).AddTicks(235),
                            email = "manager@parkir.local",
                            is_active = true,
                            name = "Zone Manager",
                            password_hash = "12345",
                            role_id = 4,
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 5,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            deleted_at = new DateTime(2026, 4, 25, 8, 41, 29, 801, DateTimeKind.Local).AddTicks(241),
                            email = "viewer@parkir.local",
                            is_active = true,
                            name = "Viewer User",
                            password_hash = "12345",
                            role_id = 5,
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        });
                });

            modelBuilder.Entity("backend.Models.Vehicle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("plate_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("vehicle_type_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("vehicle_type_id");

                    b.ToTable("vehicles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            notes = "Red Sedan",
                            plate_number = "B 1234 ABC",
                            source = "Manual",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            vehicle_type_id = 2
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            notes = "Black Motorcycle",
                            plate_number = "B 5678 XYZ",
                            source = "RFID",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            vehicle_type_id = 1
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            notes = "White Bus",
                            plate_number = "B 9012 DEF",
                            source = "Manual",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            vehicle_type_id = 3
                        },
                        new
                        {
                            id = 4,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            notes = "Blue Truck",
                            plate_number = "B 3456 GHI",
                            source = "OCR",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            vehicle_type_id = 4
                        },
                        new
                        {
                            id = 5,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            notes = "Silver Car",
                            plate_number = "B 7890 JKL",
                            source = "Manual",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            vehicle_type_id = 2
                        });
                });

            modelBuilder.Entity("backend.Models.VehicleTypes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("minimum_fee")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("vehicle_types");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            description = "Motorcycle/Scooter",
                            minimum_fee = 5000,
                            name = "Motor"
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            description = "Car/Sedan",
                            minimum_fee = 10000,
                            name = "Mobil"
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            description = "Bus/Large Vehicle",
                            minimum_fee = 25000,
                            name = "Bus"
                        },
                        new
                        {
                            id = 4,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            description = "Truck/Pickup",
                            minimum_fee = 20000,
                            name = "Truck"
                        },
                        new
                        {
                            id = 5,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            description = "Special vehicles",
                            minimum_fee = 15000,
                            name = "Kendaraan Khusus"
                        });
                });

            modelBuilder.Entity("backend.Models.Zone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("additional_fee")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("zones");

                    b.HasData(
                        new
                        {
                            id = 1,
                            additional_fee = 0,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            description = "Ground floor parking zone",
                            is_active = true,
                            name = "Zona A - Lantai 1",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 2,
                            additional_fee = 2000,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            description = "Second floor parking zone",
                            is_active = true,
                            name = "Zona B - Lantai 2",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 3,
                            additional_fee = 3000,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            description = "Third floor parking zone",
                            is_active = true,
                            name = "Zona C - Lantai 3",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 4,
                            additional_fee = 0,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            description = "Outdoor parking area",
                            is_active = true,
                            name = "Zona D - Outdoor",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        },
                        new
                        {
                            id = 5,
                            additional_fee = 10000,
                            created_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820),
                            created_by = "System",
                            description = "VIP parking zone with premium services",
                            is_active = true,
                            name = "Zona E - VIP",
                            updated_at = new DateTime(2026, 4, 25, 8, 41, 29, 799, DateTimeKind.Local).AddTicks(7820)
                        });
                });

            modelBuilder.Entity("backend.Models.FeeConfig", b =>
                {
                    b.HasOne("backend.Models.Users", "creator")
                        .WithMany()
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.VehicleTypes", "vehicle_type")
                        .WithMany()
                        .HasForeignKey("vehicle_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Zone", "zone")
                        .WithMany()
                        .HasForeignKey("zone_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("creator");

                    b.Navigation("vehicle_type");

                    b.Navigation("zone");
                });

            modelBuilder.Entity("backend.Models.FeeTier", b =>
                {
                    b.HasOne("backend.Models.FeeConfig", "fee_config")
                        .WithMany()
                        .HasForeignKey("fee_config_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fee_config");
                });

            modelBuilder.Entity("backend.Models.HolidayRate", b =>
                {
                    b.HasOne("backend.Models.VehicleTypes", "vehicle_type")
                        .WithMany()
                        .HasForeignKey("applies_to_vehicle_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Zone", "zone")
                        .WithMany()
                        .HasForeignKey("applies_to_zone_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vehicle_type");

                    b.Navigation("zone");
                });

            modelBuilder.Entity("backend.Models.MidtransCallback", b =>
                {
                    b.HasOne("backend.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("payment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("backend.Models.Payment", b =>
                {
                    b.HasOne("backend.Models.Users", "HandledByUser")
                        .WithMany()
                        .HasForeignKey("handled_by_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("transaction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HandledByUser");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("backend.Models.RfidCard", b =>
                {
                    b.HasOne("backend.Models.Employee", "employee")
                        .WithMany()
                        .HasForeignKey("employee_id");

                    b.HasOne("backend.Models.TenantMember", "pic_tenant")
                        .WithMany()
                        .HasForeignKey("pic_tenant_id");

                    b.HasOne("backend.Models.Vehicle", "vehicle")
                        .WithMany()
                        .HasForeignKey("vehicle_id");

                    b.Navigation("employee");

                    b.Navigation("pic_tenant");

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("backend.Models.RolePermission", b =>
                {
                    b.HasOne("backend.Models.Permission", "Permissions")
                        .WithMany()
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissions");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("backend.Models.TenantMember", b =>
                {
                    b.HasOne("backend.Models.MembershipPackage", "membership")
                        .WithMany()
                        .HasForeignKey("membership_id");

                    b.HasOne("backend.Models.Users", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("membership");

                    b.Navigation("user");
                });

            modelBuilder.Entity("backend.Models.Transaction", b =>
                {
                    b.HasOne("backend.Models.Gate", "EntryGate")
                        .WithMany()
                        .HasForeignKey("entry_gate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Gate", "ExitGate")
                        .WithMany()
                        .HasForeignKey("exit_gate_id");

                    b.HasOne("backend.Models.FeeConfig", "FeeConfig")
                        .WithMany()
                        .HasForeignKey("fee_config_id");

                    b.HasOne("backend.Models.HolidayRate", "HolidayRate")
                        .WithMany()
                        .HasForeignKey("holiday_rate_id");

                    b.HasOne("backend.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("member_vehicle_id");

                    b.HasOne("backend.Models.RfidCard", "RfidCard")
                        .WithMany()
                        .HasForeignKey("rfid_card_id");

                    b.HasOne("backend.Models.VehicleTypes", "VehicleType")
                        .WithMany()
                        .HasForeignKey("vehicle_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("zone_id");

                    b.Navigation("EntryGate");

                    b.Navigation("ExitGate");

                    b.Navigation("FeeConfig");

                    b.Navigation("HolidayRate");

                    b.Navigation("RfidCard");

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleType");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("backend.Models.UserLoginLogs", b =>
                {
                    b.HasOne("backend.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Models.UserLoginStats", b =>
                {
                    b.HasOne("backend.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Models.Users", b =>
                {
                    b.HasOne("backend.Models.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("backend.Models.Vehicle", b =>
                {
                    b.HasOne("backend.Models.VehicleTypes", "VehicleTypes")
                        .WithMany()
                        .HasForeignKey("vehicle_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
